In [ ]:
import torch.nn as nn
import torch


In [ ]:
class model(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out



In [ ]:
#create dataset

features = torch.rand(10,5)


model = model(features.shape[1])

model(features)

tensor([[0.3281],
        [0.3351],
        [0.3615],
        [0.3377],
        [0.2947],
        [0.3664],
        [0.3632],
        [0.3102],
        [0.2807],
        [0.3211]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.1380, -0.2882, -0.3352, -0.3023, -0.1019]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.2725], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:

class Testor(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.fc = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.fc(features)
    out = self.relu(out)
    out = self.fc2(out)
    out = self.sigmoid(out)
    return out



In [ ]:

newfeatures = torch.rand(10,5)
model = Testor(newfeatures.shape[1])
model(newfeatures)

tensor([[0.6014],
        [0.6011],
        [0.6011],
        [0.6010],
        [0.6015],
        [0.5978],
        [0.6002],
        [0.6009],
        [0.6008],
        [0.6000]], grad_fn=<SigmoidBackward0>)

In [ ]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Testor                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
model.fc.weight

Parameter containing:
tensor([[ 0.0121, -0.3078, -0.3294,  0.2877,  0.0214],
        [ 0.2193, -0.1673, -0.0643,  0.1590, -0.4232],
        [ 0.3112, -0.1751,  0.1456,  0.0183,  0.2495]], requires_grad=True)

In [ ]:
model.fc2.weight

Parameter containing:
tensor([[-0.2914, -0.1060, -0.0141]], requires_grad=True)

In [ ]:
model.fc.bias

Parameter containing:
tensor([-0.1090, -0.1457,  0.1558], requires_grad=True)

In [ ]:
model.fc2.bias

Parameter containing:
tensor([0.4149], requires_grad=True)

## Using Sequential container

In [ ]:
class sequential_model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()
    # self.network = nn.Sequential(
    #     nn.Linear(num_features,4),
    #     nn.ReLU(),
    #     nn.Linear(4,2),
    #     nn.ReLU(),
    #     nn.Linear(2,1),
    #     nn.Sigmoid())

  def forward(self,features):
    return self.sigmoid(self.linear(features))

In [ ]:
features = torch.rand(20,6)

In [ ]:
model = sequential_model(features.shape[1])

In [ ]:
model(features)

tensor([[0.4314],
        [0.4322],
        [0.4401],
        [0.4307],
        [0.4416],
        [0.4349],
        [0.4356],
        [0.4442],
        [0.4464],
        [0.4362],
        [0.4402],
        [0.4384],
        [0.4454],
        [0.4594],
        [0.4403],
        [0.4445],
        [0.4320],
        [0.4308],
        [0.4402],
        [0.4442]], grad_fn=<SigmoidBackward0>)

In [ ]:
summary(model,input_size=(20,6))

Layer (type:depth-idx)                   Output Shape              Param #
sequential_model                         [20, 1]                   --
├─Sequential: 1-1                        [20, 1]                   --
│    └─Linear: 2-1                       [20, 4]                   28
│    └─ReLU: 2-2                         [20, 4]                   --
│    └─Linear: 2-3                       [20, 2]                   10
│    └─ReLU: 2-4                         [20, 2]                   --
│    └─Linear: 2-5                       [20, 1]                   3
│    └─Sigmoid: 2-6                      [20, 1]                   --
Total params: 41
Trainable params: 41
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Dataset loading

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [ ]:
df.drop(columns = ['id','Unnamed: 32'],inplace=True)

In [ ]:
X_train,x_test,Y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,:1],test_size=0.2,random_state=42)

In [ ]:
encoder = LabelEncoder()
Y_train = encoder.fit_transform(Y_train)
y_test = encoder.fit_transform(y_test)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
x_test = scaler.fit_transform(x_test)

In [ ]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
x_test_tensor = torch.tensor(x_test, dtype=torch.float32)
Y_train_tensor = torch.tensor(Y_train, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [ ]:
print(X_train_tensor.dtype)
print(x_test_tensor.dtype)
print(Y_train_tensor.dtype)
print(y_test_tensor.dtype)

torch.float32
torch.float32
torch.float32
torch.float32


## important parameters

In [ ]:
learning_rate = 0.025
epochs = 50000

## USING TRAINING PIPELINE

In [ ]:
loss_function = nn.BCELoss()

In [ ]:
model = sequential_model(X_train_tensor.shape[1])

In [ ]:
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

In [ ]:
for epoch in range(epochs):

  #forward pass
  y_pred = model(X_train_tensor)

  #loss calculation
  loss=loss_function(y_pred,Y_train_tensor.view(-1,1))

  #zero gradients
  optimizer.zero_grad()


  #backward pass
  loss.backward()

  #update weights
  # with torch.no_grad():
  #   model.linear.weight -= learning_rate * model.linear.weight.grad
  #   model.linear.bias -= learning_rate * model.linear.bias.grad

  optimizer.step()

  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()
  print(f'loss at epoch {epoch+1} is {loss.item()}')


Streaming output truncated to the last 5000 lines.
loss at epoch 45001 is 0.04231001064181328
loss at epoch 45002 is 0.042309872806072235
loss at epoch 45003 is 0.0423097237944603
loss at epoch 45004 is 0.042309585958719254
loss at epoch 45005 is 0.04230944439768791
loss at epoch 45006 is 0.04230930283665657
loss at epoch 45007 is 0.04230916500091553
loss at epoch 45008 is 0.042309027165174484
loss at epoch 45009 is 0.042308881878852844
loss at epoch 45010 is 0.0423087440431118
loss at epoch 45011 is 0.04230860248208046
loss at epoch 45012 is 0.042308464646339417
loss at epoch 45013 is 0.04230832681059837
loss at epoch 45014 is 0.04230818152427673
loss at epoch 45015 is 0.04230804368853569
loss at epoch 45016 is 0.04230790212750435
loss at epoch 45017 is 0.042307764291763306
loss at epoch 45018 is 0.04230762645602226
loss at epoch 45019 is 0.042307473719120026
loss at epoch 45020 is 0.04230734333395958
loss at epoch 45021 is 0.04230719804763794
loss at epoch 45022 is 0.0423070639371871

In [ ]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred_class = (y_pred > 0.6).float()
  accuracy = (y_pred_class == y_test_tensor).float().mean()
  print(f'accuracy : {accuracy}')

accuracy : 0.5344721674919128
