## Dataset and Dataloader class

In [ ]:
from sklearn.datasets import make_classification
import torch

In [ ]:
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [ ]:
X = torch.from_numpy(X).float()
y = torch.from_numpy(y).long()

In [ ]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [ ]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
from torch.utils.data import Dataset,DataLoader

In [ ]:
class CustomDataset(Dataset):
    def __init__(self,features,labels):
        self.features = features
        self.labels = labels
    def __len__(self):
        return self.features.shape[0]
    def __getitem__(self,idx):
        return self.features[idx],self.labels[idx]

In [ ]:
dataset = CustomDataset(X,y)

In [ ]:
len(dataset)

10

In [ ]:
dataset[4]

(tensor([-1.9629, -0.9923]), tensor(0))

In [ ]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=False)

In [ ]:
for batch_features,batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("-"*50)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------


In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [ ]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return len(self.features)

  def __getitem__(self, idx):

    return self.features[idx], self.labels[idx]


In [ ]:

train_dataset= CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [ ]:
train_dataset[10]

(tensor([ 0.7220,  0.5243,  0.7239,  0.5858, -0.0630,  0.5068,  0.5271,  0.2553,
          0.2966, -0.8906,  0.1725, -0.5431,  0.0518,  0.0808, -0.4534, -0.0607,
          0.1558,  0.0077,  0.8847, -0.4339,  0.7579,  0.5463,  0.7684,  0.5933,
          0.9984,  0.7656,  1.2467,  0.9838,  3.1750,  0.0992]),
 tensor(1.))

In [ ]:
train_loader = DataLoader(train_dataset,batch_size=15,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=15,shuffle=True)

In [ ]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 4)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(4, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [ ]:
learning_rate = 0.025
epochs = 250

In [ ]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

In [ ]:

# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6697933077812195
Epoch: 2, Loss: 0.5761351585388184
Epoch: 3, Loss: 0.3056534230709076
Epoch: 4, Loss: 0.37980324029922485
Epoch: 5, Loss: 0.25551700592041016
Epoch: 6, Loss: 0.2707056701183319
Epoch: 7, Loss: 0.06578593701124191
Epoch: 8, Loss: 0.16114500164985657
Epoch: 9, Loss: 0.21913130581378937
Epoch: 10, Loss: 0.02430465631186962
Epoch: 11, Loss: 0.022494932636618614
Epoch: 12, Loss: 0.22015181183815002
Epoch: 13, Loss: 0.12255774438381195
Epoch: 14, Loss: 0.07258844375610352
Epoch: 15, Loss: 0.1955089420080185
Epoch: 16, Loss: 0.040438212454319
Epoch: 17, Loss: 0.08525120466947556
Epoch: 18, Loss: 0.10209228843450546
Epoch: 19, Loss: 0.2131202667951584
Epoch: 20, Loss: 0.1366109549999237
Epoch: 21, Loss: 0.05056419223546982
Epoch: 22, Loss: 0.03006851300597191
Epoch: 23, Loss: 0.02889799140393734
Epoch: 24, Loss: 0.005125433672219515
Epoch: 25, Loss: 0.012347656302154064
Epoch: 26, Loss: 0.022598879411816597
Epoch: 27, Loss: 0.03969074413180351
Epoch: 28, Loss

In [ ]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        print(f"view: {y_pred.view(-1)}")
        print(f"reshape: {y_pred.reshape(1,-1)}")
        print(f"labels: {batch_labels}")
        print("-"*50)
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        # print(batch_accuracy)
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

view: tensor([0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0.])
reshape: tensor([[0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0.]])
labels: tensor([0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0.])
--------------------------------------------------
view: tensor([1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0.])
reshape: tensor([[1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0.]])
labels: tensor([1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0.])
--------------------------------------------------
view: tensor([0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1.])
reshape: tensor([[0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1.]])
labels: tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.])
--------------------------------------------------
view: tensor([1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0.])
reshape: tensor([[1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0.

In [ ]:
model.eval()
accuracy_list = []
with torch.no_grad():
  for batch_features,batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred>0.8).float()

    batch_accuracy = (y_pred.reshape(1,-1) == batch_labels).float().mean().item()
    print(batch_accuracy)
    accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list)/len(accuracy_list)
print(f'Accuracy :{overall_accuracy}')

0.9333333373069763
0.9333333373069763
0.8666666746139526
1.0
0.9333333373069763
1.0
0.9333333373069763
1.0
Accuracy :0.9500000029802322
