In [2]:
import torch

print(torch.__version__)

2.10.0+cu128


In [3]:
if torch.cuda.is_available():
    print('GPU is available')
    print(torch.cuda.get_device_name(0))
else:
    print('GPU is not available')


GPU is available
Tesla T4


In [4]:
a = torch.empty(3,4)

In [5]:
type(a)

torch.Tensor

In [6]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
torch.rand(5,2)

tensor([[0.6048, 0.5115],
        [0.8308, 0.3139],
        [0.2174, 0.4014],
        [0.6445, 0.0437],
        [0.3080, 0.0283]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.tensor([[3,4,5],[2,4,5]])

tensor([[3, 4, 5],
        [2, 4, 5]])

## shapes


In [13]:
tens = torch.tensor([[3,45,5],[5,6,2]])
tens.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(tens)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.ones_like(tens)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
torch.zeros_like(tens)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [27]:
torch.rand_like(tens,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor data type

In [22]:
#check datatype
tens.dtype

In [24]:
#assign_datatype
torch.tensor([2,2.0,3.0],dtype=torch.float64)

tensor([2., 2., 3.], dtype=torch.float64)

In [25]:
#using to()
tens.to(torch.float16)

tensor([[ 3., 45.,  5.],
        [ 5.,  6.,  2.]], dtype=torch.float16)

# Mathematical Operations

In [32]:
x = torch.rand(2,2)

In [33]:
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [34]:
#addition
x + 2



tensor([[2.9969, 2.7565],
        [2.2239, 2.3023]])

In [35]:
#multiplication
x *3


tensor([[2.9907, 2.2695],
        [0.6717, 0.9070]])

In [36]:
#division
x / 4



tensor([[0.2492, 0.1891],
        [0.0560, 0.0756]])

In [37]:
#int division
(x*100 )//3



tensor([[33., 25.],
        [ 7., 10.]])

In [38]:
#mod
(x*100 )//3 % 2

tensor([[1., 1.],
        [1., 0.]])

In [39]:
#power
x**3

tensor([[0.9907, 0.4330],
        [0.0112, 0.0276]])

In [41]:
#abs
c = torch.tensor([-2,-3,-4])
torch.abs(c)

tensor([2, 3, 4])

In [53]:
d = torch.tensor([8,3.9,-1.2,1.5])

In [54]:
#round
torch.round(d)

tensor([ 8.,  4., -1.,  2.])

In [55]:
#ceil
torch.ceil(d)

tensor([ 8.,  4., -1.,  2.])

In [56]:
#floor
torch.floor(d)

tensor([ 8.,  3., -2.,  1.])

In [57]:
#clamp
torch.clamp(d,min=1,max = 4)

tensor([4.0000, 3.9000, 1.0000, 1.5000])

## Redcution operation

In [94]:
e = torch.randint(size=(3,4),low = 0,high = 39,dtype=torch.float64)
e

tensor([[26., 16., 38., 24.],
        [29., 19., 17., 37.],
        [36., 20.,  9., 17.]], dtype=torch.float64)

In [95]:
torch.sum(e)

tensor(288., dtype=torch.float64)

In [96]:
torch.sum(e,dim=0)

tensor([91., 55., 64., 78.], dtype=torch.float64)

In [97]:
torch.sum(e,dim=1
          )

tensor([104., 102.,  82.], dtype=torch.float64)

In [98]:
torch.mean(e)

tensor(24., dtype=torch.float64)

In [99]:
torch.mean(e,dim=0)

tensor([30.3333, 18.3333, 21.3333, 26.0000], dtype=torch.float64)

In [100]:
torch.mean(e,dim=1)

tensor([26.0000, 25.5000, 20.5000], dtype=torch.float64)

In [101]:
torch.std(e)

tensor(9.3711, dtype=torch.float64)

In [102]:
torch.var(e)

tensor(87.8182, dtype=torch.float64)

In [103]:
torch.corrcoef(e)

tensor([[ 1.0000, -0.2367, -0.4078],
        [-0.2367,  1.0000,  0.3642],
        [-0.4078,  0.3642,  1.0000]], dtype=torch.float64)

In [104]:
torch.argmax(e)

tensor(2)

In [105]:
torch.argmin(e)

tensor(10)

## Matrix Operations

In [106]:
m = torch.randint(size=(3,3),low = 0,high = 39,dtype=torch.float64)
n = torch.randint(size=(3,3),low = 0,high = 39,dtype=torch.float64)

In [107]:
m

tensor([[13.,  0., 37.],
        [15.,  0., 23.],
        [30.,  2., 13.]], dtype=torch.float64)

In [108]:
n

tensor([[20., 26., 25.],
        [ 9., 27., 29.],
        [ 8., 13.,  6.]], dtype=torch.float64)

In [113]:
#matrix multiplication
torch.matmul(m,n)

tensor([[ 556.,  819.,  547.],
        [ 484.,  689.,  513.],
        [ 722., 1003.,  886.]], dtype=torch.float64)

In [115]:
#dot product
vector1 = torch.tensor([2,3,4])
vector2 = torch.tensor([5,6,7])

In [116]:
torch.dot(vector1,vector2)

tensor(56)

In [118]:
torch.transpose(m,0,1)

tensor([[13., 15., 30.],
        [ 0.,  0.,  2.],
        [37., 23., 13.]], dtype=torch.float64)

In [119]:
torch.det(m)

tensor(512.0000, dtype=torch.float64)

In [120]:
torch.adjoint(m)

tensor([[13., 15., 30.],
        [ 0.,  0.,  2.],
        [37., 23., 13.]], dtype=torch.float64)

In [121]:
torch.inverse(m)

tensor([[-0.0898,  0.1445,  0.0000],
        [ 0.9668, -1.8379,  0.5000],
        [ 0.0586, -0.0508,  0.0000]], dtype=torch.float64)

## Comparision Operations


In [123]:
i = torch.randint(size=(3,3),low = 0,high = 39,dtype=torch.float64)
j = torch.randint(size=(3,3),low = 0,high = 39,dtype=torch.float64)



In [124]:
i < j

tensor([[False,  True,  True],
        [ True, False,  True],
        [ True,  True,  True]])

In [125]:
i > j

tensor([[ True, False, False],
        [False,  True, False],
        [False, False, False]])

In [126]:
i == j

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [127]:
i != j

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [128]:
i <= j

tensor([[False,  True,  True],
        [ True, False,  True],
        [ True,  True,  True]])

In [129]:
i >= j

tensor([[ True, False, False],
        [False,  True, False],
        [False, False, False]])

## Special Functions

In [130]:
k = torch.randint(size=(3,3),low = 0,high = 39,dtype=torch.float64)

In [131]:
torch.log(k)

tensor([[2.7081, 2.9957, 2.1972],
        [3.5835, 1.3863, 2.9444],
        [1.9459, 3.1355, 2.7081]], dtype=torch.float64)

In [132]:
torch.exp(k)

tensor([[3.2690e+06, 4.8517e+08, 8.1031e+03],
        [4.3112e+15, 5.4598e+01, 1.7848e+08],
        [1.0966e+03, 9.7448e+09, 3.2690e+06]], dtype=torch.float64)

In [133]:
torch.sqrt(k)

tensor([[3.8730, 4.4721, 3.0000],
        [6.0000, 2.0000, 4.3589],
        [2.6458, 4.7958, 3.8730]], dtype=torch.float64)

In [134]:
torch.sigmoid(k)

tensor([[1.0000, 1.0000, 0.9999],
        [1.0000, 0.9820, 1.0000],
        [0.9991, 1.0000, 1.0000]], dtype=torch.float64)

In [136]:
torch.softmax(k,dim=0)

tensor([[7.5826e-10, 4.7426e-02, 4.4581e-05],
        [1.0000e+00, 5.3371e-09, 9.8197e-01],
        [2.5437e-13, 9.5257e-01, 1.7985e-02]], dtype=torch.float64)

In [137]:
torch.relu(k)

tensor([[15., 20.,  9.],
        [36.,  4., 19.],
        [ 7., 23., 15.]], dtype=torch.float64)

## inplace Operations

In [139]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [147]:
m

tensor([[0.9792, 0.4947, 0.3617],
        [0.9687, 0.0359, 0.3041]])

In [146]:
n

tensor([[0.9867, 0.1290, 0.6887],
        [0.1637, 0.0899, 0.3139]])

In [140]:
m + n

tensor([[1.9659, 0.6237, 1.0504],
        [1.1323, 0.1258, 0.6180]])

In [141]:
m.add_(n)

tensor([[1.9659, 0.6237, 1.0504],
        [1.1323, 0.1258, 0.6180]])

In [142]:
m

tensor([[1.9659, 0.6237, 1.0504],
        [1.1323, 0.1258, 0.6180]])

In [143]:
m.relu_()

tensor([[1.9659, 0.6237, 1.0504],
        [1.1323, 0.1258, 0.6180]])

In [145]:
m.sub_(n)

tensor([[0.9792, 0.4947, 0.3617],
        [0.9687, 0.0359, 0.3041]])

## copying a tensor

In [153]:
a = torch.rand(2,4)

In [154]:
a

tensor([[0.0623, 0.5967, 0.0829, 0.8185],
        [0.4964, 0.0589, 0.9840, 0.5836]])

In [155]:
b = a

In [156]:
b

tensor([[0.0623, 0.5967, 0.0829, 0.8185],
        [0.4964, 0.0589, 0.9840, 0.5836]])

In [157]:
a[0][0] = 0

In [158]:
a

tensor([[0.0000, 0.5967, 0.0829, 0.8185],
        [0.4964, 0.0589, 0.9840, 0.5836]])

In [159]:
b

tensor([[0.0000, 0.5967, 0.0829, 0.8185],
        [0.4964, 0.0589, 0.9840, 0.5836]])

In [165]:
id(a)

140261601667472

In [161]:
id(b)

140261601667472

In [162]:
b = a.clone()

In [163]:
id(b)

140261610746288

In [166]:
a[0][1] = 1

In [167]:
a

tensor([[0.0000, 1.0000, 0.0829, 0.8185],
        [0.4964, 0.0589, 0.9840, 0.5836]])

In [168]:
b

tensor([[0.0000, 0.5967, 0.0829, 0.8185],
        [0.4964, 0.0589, 0.9840, 0.5836]])

## Tensor Operation on GPU

In [170]:
torch.cuda.is_available()

True

In [171]:
device = torch.device('cuda')

In [172]:
device

device(type='cuda')

In [174]:
#create new tensor on GPU
torch.rand((5,3),device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896],
        [0.3737, 0.0823, 0.2851],
        [0.4433, 0.2989, 0.4175],
        [0.2687, 0.0927, 0.2317]], device='cuda:0')

In [175]:
y = torch.rand(2,3)
y

tensor([[0.6737, 0.4738, 0.9336],
        [0.2557, 0.1506, 0.7856]])

In [178]:
w= y.to(device=device)

In [179]:
w + 5

tensor([[5.6737, 5.4738, 5.9336],
        [5.2557, 5.1506, 5.7856]], device='cuda:0')

In [182]:
size = 20000
import time

In [183]:
mat1 = torch.rand(size,size)
mat2 = torch.rand(size,size)

In [184]:
start_time = time.time()
res =torch.matmul(mat1,mat2)
cpu_time = time.time() - start_time
print(f'time taken by cpu {cpu_time:.4f}')

time taken by cpu 143.2354


In [185]:
gpu_mat1 = mat1.to(device)
gpu_mat2 = mat2.to(device)

start_time = time.time()
res =torch.matmul(gpu_mat1,gpu_mat2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time
print(f'time taken by gpu {gpu_time:.4f}')

time taken by gpu 3.8439


In [186]:
print('\nSpeedup (cpu/gpu):',cpu_time/gpu_time)


Speedup (cpu/gpu): 37.26350108108138


# Reshape Tensors

In [2]:
import torch

In [4]:
a = torch.ones(2,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
a.reshape(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [6]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1.])

In [10]:
b = torch.rand(2,3,4)

In [11]:
b

tensor([[[0.2494, 0.6985, 0.8182, 0.5744],
         [0.3294, 0.1095, 0.1730, 0.7271],
         [0.2959, 0.9785, 0.4228, 0.4005]],

        [[0.5376, 0.0223, 0.3196, 0.7097],
         [0.3545, 0.4573, 0.5028, 0.8667],
         [0.7220, 0.4295, 0.1380, 0.8839]]])

In [13]:
#permute
b.permute(2,1,0)

tensor([[[0.2494, 0.5376],
         [0.3294, 0.3545],
         [0.2959, 0.7220]],

        [[0.6985, 0.0223],
         [0.1095, 0.4573],
         [0.9785, 0.4295]],

        [[0.8182, 0.3196],
         [0.1730, 0.5028],
         [0.4228, 0.1380]],

        [[0.5744, 0.7097],
         [0.7271, 0.8667],
         [0.4005, 0.8839]]])

In [20]:
#unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(dim=3).shape

torch.Size([226, 226, 3, 1])

In [15]:
c

tensor([[[0.3586, 0.7712, 0.8541],
         [0.5901, 0.4111, 0.6290],
         [0.1105, 0.5351, 0.0311],
         ...,
         [0.6765, 0.9028, 0.5257],
         [0.4884, 0.7169, 0.5042],
         [0.9830, 0.0901, 0.6138]],

        [[0.2018, 0.3279, 0.3435],
         [0.2447, 0.8015, 0.6348],
         [0.2683, 0.2486, 0.6097],
         ...,
         [0.9311, 0.7132, 0.3879],
         [0.8162, 0.5863, 0.4824],
         [0.6407, 0.0490, 0.3277]],

        [[0.3977, 0.4631, 0.0011],
         [0.4786, 0.5612, 0.8991],
         [0.2114, 0.4980, 0.6948],
         ...,
         [0.8546, 0.6078, 0.9558],
         [0.1204, 0.4612, 0.5401],
         [0.9266, 0.2922, 0.6195]],

        ...,

        [[0.1403, 0.4095, 0.2064],
         [0.1268, 0.3022, 0.1465],
         [0.5086, 0.1702, 0.3953],
         ...,
         [0.9548, 0.0646, 0.7103],
         [0.1330, 0.4061, 0.6329],
         [0.4903, 0.6195, 0.8064]],

        [[0.2451, 0.7531, 0.5684],
         [0.8891, 0.3504, 0.2648],
         [0.

In [27]:
#squeeze

d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## Numpy and Pytorch conversion

In [29]:
import numpy as np

In [28]:
t = torch.tensor([2,4,8])

In [34]:
x = t.numpy()

In [35]:
type(x)

numpy.ndarray

In [36]:
arr = np.array([2,6,9])

In [37]:
ans = torch.from_numpy(arr)

In [38]:
type(ans)

torch.Tensor